print("Первая стадия это:")
first = input()
print("Вторая стадия это:")
second = input()
print("Третья стадия это:")
third = input()
print("Четвертая стадия это:")
fourth = input()
print("Пятая стадия это:")
fifth = input()
print("Шестая стадия это:")
sixth = input()
print("Седьмая стадия это:")
seventh = input()
print(first, second, third, fourth, fifth, sixth, seventh, sep=' => ')